### ISSUE TITLE
cannot import name 'Workshop' from 'protein_fuser' 

### ISSUE THREAD

**Issue by LAJ-THU** [matteoferla/Christmas_tree_protein#1]
Thanks for your wonderful design! But I cannot seem to run the program correctly.

I copied the `protein_fusers.py` file from [protein_fusers](https://github.com/matteoferla/protein_fuser) into the working directory, and run the code given in the ProtoTree section. However, an error message came up:

`cannot import name 'Workshop' from 'protein_fuser' ([/Users/liuanji/Desktop/christmas_tree/Christmas_tree_protein/protein_fuser.py](http://localhost:8888/lab/tree/protein_fuser.py))`

I checked the protien_fuser.py file, but found no class named Workshop, why does this happen? Could you give me some suggestions?

**Comment by matteoferla** [comment]
Uhm. It was 5 years ago, `Workshop` was renamed `Fuser` IIRC, but the class does not seem to get used in the first place in the example. I have never been a fan of functions that change global settings, so I'd bet the Workshop instance has a PyMOL instance as an attribute as opposed to pollute the main namespace secretly. So I'll delete that line in the example.

I should say this code was meant to be a one-off not a functional usable module...

However, the world has changed a lot since 2019: pandemic apart, AI is a household word. Denoising diffusion is perfect for hallucinating protein. This tree was done parametrically, but were I to do it again I would use RFdiffusion or other framework. Namely, I'd get a STL file from the web (may cost a quid or two) -> boolean voxel grid -> magically apply this as a sigmoid penalty to the loss function in RFdiffusion. The 'magic' actually covers a lot of behind the scenes effort as three assumptions are in place, the guiding force or correction (=gradient of the potential in RFdiffusion, [ca_grad](https://github.com/RosettaCommons/RFdiffusion/blob/b44206a2a79f219bb1a649ea50603a284c225050/rfdiffusion/inference/utils.py#L484)) used by can be easily tweaked, the diffusion is in Euclidean space and the grid is aligned (it isn't).
